### PR TITLE
fixed card style like base44 design

### LINKED ISSUE #240: Small changes in cards in main page are needed
Right now on the main page we have those cards: 

Image

We need to make them look like this : 

Image

The background should be `rgb(30 41 59 / 0.5)` or `#1e293b80` in hexa. 

For more reference check out the base44 design

### PR DESCRIPTION
**Pull request by francescolaudato**
1. Fixed style for card based on the design

Close #240 

NOTE: I had trouble changing the icon for the “Performance analytics” card because I couldn't find it here https://tabler.io/icons

### CODE REVIEW

File: src/pages/Home/Components/ExploreToolkit.tsx [hunk 1]
```diff
@@ -1,46 +1,57 @@
...
 
-// TODO - Make this more according to the design inside base44
 export const ExploreToolkit = () => {
   const { t } = useTranslation();
   const { CARDS_DATA } = useExploreToolkitCardsData();
 
   return (
-    <div className={classes.container}>
-      <Typography variant='h1' className={classes.title}>
+    <Container style={exploreToolkitStyles.container}>
```
Comment (Tamir198) [inline src/pages/Home/Components/ExploreToolkit.tsx]: Why do we need this component over a regular div? they are doing the same and I would really want us to only use the shared ui component as much as possilbe

File: src/pages/Home/Components/ExploreToolkit.tsx [hunk 2]
```diff
@@ -1,46 +1,57 @@
...
         {t('explore_toolkit_title_part2')}
       </Typography>
-      <Typography variant='body' className={classes.description}>
+
+      <Typography variant="body" style={exploreToolkitStyles.description}>
         {t('explore_toolkit_description')}
       </Typography>
-      <div className={classes.grid}>
+
+      <SimpleGrid cols={{ base: 1, md: 3 }} spacing="xl">
```
Comment (Tamir198) [inline src/pages/Home/Components/ExploreToolkit.tsx]: Please avoid using mantine components directly, the div with the class if just fine, i dont want to have developer depend on this library when deveoping the website

**Review by Tamir198 — CHANGES_REQUESTED** [review]
Looks good in the UI, I left you some comments about the code

**Review by Tamir198 — APPROVED** [review]
Great thank you for this contribution
